
#ifndef API_SQL_QUERY_BUILDER_H
#define API_SQL_QUERY_BUILDER_H

#ifdef SQLQUERYBUILDER_STATIC_DEFINE
#  define API_SQL_QUERY_BUILDER
#  define SQLQUERYBUILDER_NO_EXPORT
#else
#  ifndef API_SQL_QUERY_BUILDER
#    ifdef SqlQueryBuilder_EXPORTS
        /* We are building this library */
#      define API_SQL_QUERY_BUILDER __declspec(dllexport)
#    else
        /* We are using this library */
#      define API_SQL_QUERY_BUILDER __declspec(dllimport)
#    endif
#  endif

#  ifndef SQLQUERYBUILDER_NO_EXPORT
#    define SQLQUERYBUILDER_NO_EXPORT 
#  endif
#endif

#ifndef SQLQUERYBUILDER_DEPRECATED
#  define SQLQUERYBUILDER_DEPRECATED __declspec(deprecated)
#endif

#ifndef SQLQUERYBUILDER_DEPRECATED_EXPORT
#  define SQLQUERYBUILDER_DEPRECATED_EXPORT API_SQL_QUERY_BUILDER SQLQUERYBUILDER_DEPRECATED
#endif

#ifndef SQLQUERYBUILDER_DEPRECATED_NO_EXPORT
#  define SQLQUERYBUILDER_DEPRECATED_NO_EXPORT SQLQUERYBUILDER_NO_EXPORT SQLQUERYBUILDER_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef SQLQUERYBUILDER_NO_DEPRECATED
#    define SQLQUERYBUILDER_NO_DEPRECATED
#  endif
#endif

#endif /* API_SQL_QUERY_BUILDER_H */
